### ISSUE TITLE
Minecraft Mod Issue

### ISSUE THREAD

**Issue by BlazeyDann** [micdoodle8/MicdoodleCore#15]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.224.jar)
  DLFMLCorePlugin (DynamicLights_1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/17/19 4:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Gravitation Suite (gravisuite)
Caused by: java.lang.NoClassDefFoundError: ic2/core/item/tool/ItemElectricTool$ToolClass
	at com.chocohead.gravisuite.Config.loadConfig(Gravisuite.java:171)
	at com.chocohead.gravisuite.Gravisuite.load(Gravisuite.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: ic2.core.item.tool.ItemElectricTool$ToolClass
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5491899208 bytes (5237 MB) / 6395265024 bytes (6099 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 5 total; -XX:+UseG1GC -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1 -Xmx6144M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2824 Optifine OptiFine_1.12.2_HD_U_E3 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version           | Source                                          | Signature                                |
	|:----- |:--------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                   | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCH   | mcp                         | 9.42              | minecraft.jar                                   | None                                     |
	| LCH   | FML                         | 8.0.99.99         | forge-1.12.2-14.23.5.2824.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                       | 14.23.5.2824      | forge-1.12.2-14.23.5.2824.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore               |                   | minecraft.jar                                   | None                                     |
	| LCH   | damageindicatorsmod         | 1.0               | 1.12.2DamageIndicatorsMod_3.5.1.jar             | None                                     |
	| LCH   | bspkrscore                  | 7.6.0.1           | 1.12bspkrsCore_universal_7.6.0.1.jar            | None                                     |
	| LCH   | treecapitator               | 1.43.0            | 1.12TreeCapitator_client_1.43.0.jar             | None                                     |
	| LCH   | appliedenergistics2         | rv6-stable-4      | appliedenergistics2_rv6_stable_4.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | backpack                    | 3.0.2             | backpack_3.0.2_1.12.2.jar                       | None                                     |
	| LCH   | baubles                     | 1.5.2             | Baubles_1.12_1.5.2.jar                          | None                                     |
	| LCH   | codechickenlib              | 3.2.3.358         | CodeChickenLib_1.12.2_3.2.3.358_universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                | 2.0.2             | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                    | 4.5.1             | CoFHCore-1.12.2-4.5.1.18-universal.jar          | None                                     |
	| LCH   | cofhworld                   | 1.2.0             | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | craftingtweaks              | 8.1.5             | CraftingTweaks_1.12.1_8.1.5.jar                 | None                                     |
	| LCH   | dynamiclights               | 1.4.8             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_onfire        | 1.0.7             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_creepers      | 1.0.6             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_dropitems     | 1.1.0             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_entityclasses | 1.0.1             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_mobequipment  | 1.1.0             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_flamearrows   | 1.0.1             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_floodlights   | 1.0.3             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_otherplayers  | 1.0.9             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_theplayer     | 1.1.3             | DynamicLights_1.12.2.jar                        | None                                     |
	| LCH   | ic2                         | 2.8.171-ex112     | industrialcraft-2-2.8.171-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | galacticraftcore            | 4.0.2.220         | GalacticraftCore-1.12.2-4.0.2.224.jar           | None                                     |
	| LCH   | galacticraftplanets         | 4.0.2.220         | Galacticraft-Planets-1.12.2-4.0.2.224.jar       | None                                     |
	| LCH   | gokistats                   | @version@         | gokiStats_1.12.2_1.2.5.jar                      | None                                     |
	| LCE   | gravisuite                  | 3.1.0             | GravitationSuite_1.12.2_3.1.0.jar               | None                                     |
	| LC    | ironchest                   | 1.12.2-7.0.67.844 | ironchest_1.12.2_7.0.67.844.jar                 | None                                     |
	| LC    | jei                         | 4.15.0.291        | jei_1.12.2_4.15.0.291.jar                       | None                                     |
	| LC    | journeymap                  | 1.12.2-5.5.5b8    | journeymap_1.12.2_5.5.5b8.jar                   | None                                     |
	| LC    | millenaire                  | Millénaire 7.2.1  | millenaire_1.12.2_7.2.1.jar                     | None                                     |
	| LC    | nei                         | 2.4.2             | NotEnoughItems_1.12.2_2.4.2.240_universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | thaumcraft                  | 6.1.BETA20        | thaumcraft-mod-1_12_2.jar                       | None                                     |
	| LC    | thermalfoundation           | 2.5.0             | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion            | 5.5.0             | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.224.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
DLFMLCorePlugin (DynamicLights_1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	AE2 Version: stable rv6-stable-4 for Forge 14.23.5.2768
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 950/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MJRLegends** [comment]
Why would you think this is a micdoodle8 core issue?

**Comment by radfast** [comment]
>   net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Gravitation Suite (gravisuite)
